//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharityImage
    {
        public int Id { get; set; }
        public int CharityId { get; set; }
        public string ImageSource { get; set; }
        public byte[] Description { get; set; }
    
        public virtual Charity Charity { get; set; }
    }
}
