//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharityComment
    {
        public int Id { get; set; }
        public Nullable<int> CharityId { get; set; }
        public string Author { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual Charity Charity { get; set; }
    }
}
